name : Deploy poinku
on:
  push:
    branches: [ deploy ]

jobs:
  first:
    name: Pull from github poinku
    runs-on: ubuntu-latest
    steps:
    - name: test deploy dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          export COMPOSER_ALLOW_SUPERUSER=1
          cd ${{ secrets.DIR }}
          git pull origin deploy
          composer update
